name: Test Nginx Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image from Dockerfile
      run: |
        cd nginx-proxy
        docker build -t test-nginx .
        
    - name: Run container from built image
      run: |
        docker run -d -p 8080:80 --name test-nginx-container test-nginx
        
    - name: Test web server
      run: |
        sleep 5
        curl http://localhost:8080/
        echo "✅ Nginx container is working!"
        
    - name: Clean up
      run: |
        docker stop test-nginx-container || true
        docker rm test-nginx-container || true
